version: '3.9'

services:
  notifications:
    build: ./
    command:
      - ./notifications
    ports:
      - "8081:8080"
    depends_on:
      - db
  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5436:5432"
    volumes:
      - './schema.sql:/docker-entrypoint-initdb.d/schema.sql'